### PR TITLE
Better use of starts with v

### PR DESCRIPTION
**Pull request by RoXuS**
Better use of starts with v

### CODE REVIEW

**Comment by ije** [comment]
thx, i am thinking that maybe we should create a promotion to let user choose the 'v' prefix for the tag or not, because normally we don't put 'v' in `const version="1.0.0"` but put it in tag 'v1.0.0'

**Comment by RoXuS** [comment]
You mean to add 12 choices here:
image
Instead of these 6?

**Comment by ije** [comment]
i mean after this we can have an option to rename the tag

**Comment by RoXuS** [comment]
oh ok, what do you think of --startsWithV or --noStartsWithV ?

**Comment by ije** [comment]
it could be better to allow people input the tag name instead of flag:

```
upgrade to: 1
tag name (default is v1.0.0): |
```

**Comment by ije** [comment]
as default the tag name always starts with 'v', this 'v' is different with 'v' in `const version="v1.0.0"`

**Comment by RoXuS** [comment]
hum I don't find it "usable". There will be several of us to use the project and each time we have to indicate the planned version, it's not optimal, right?

**Comment by ije** [comment]
sorry i forgot the PR, i will merge it now, thank you @RoXuS

**Comment by RoXuS** [comment]
oh thx!

**Pull request merged**
